#!/usr/bin/python3
import pymysql
import cgi,cgitb
cgitb.enable()
form = cgi.FieldStorage()
print("Content-type:text/html\r\n\r\n")

id=form.getvalue('sid')
db = pymysql.connect(host="localhost",user="root",password="",database="addweb")
cursor = db.cursor()
cursor.execute("select * from student where id='%s'"%(id))
data=cursor.fetchall()
print("<html>")
print("<head>")
print("<title>Update</title>")
print("<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>")
print("<link rel='stylesheet' href='css/style.css'>")
print("</head")
print("<body>")
for row in data:
    id=row[0]
    fullname=row[1]
    password=row[2]
    email=row[3]
    mobile=row[4]
    print("<center>")
    print("<h2  align='center'>UPDATE DETAILS</label><br><br>")
    print("<form action='update.py?sid=%d' method='POST'>"%(id))
    print("<input type='hidden' name='id'>")
    print("<table cellpadding='20' cellspacing='20' style='border:2px solid grey; border-radius:5px;' >")
    print("<tr >")
    print("<td colspan='5'>")
    print("</td>")
    print("</tr>")
    print("<tr>")
    print("<td>  Id </td>")
    print("<td> <input type='text' class='input-value' name='id' id='id' value='%s'> </td>"%(id))
    print("</tr>")
    print("<tr>")
    print("<td> Fullname </td>")
    print("<td> <input type='text' class='input-value' name='fullname' id='fullname' value='%s'> </td>"%(fullname))
    print("</tr>")
    print("<tr>")
    print("<td>Password</td>")
    print("<td><input type='password' class='input-value' name='password' id='password' value='%s' ></td>"%(password))
    print("</tr>")
    print("<tr>")
    print("<td>Email:</td>")
    print("<td> <input type='email' class='input-value' name='email' id='email' value='%s'> </td>"%(email))
    print("</tr>")
    print("<tr>")
    print("<td><label >Mobile:</td>")
    print("<td> <input type='number' class='input-value' name='mobile' id='mobile' value='%s'> </td>"%(mobile))
    print("</tr>")
    print("<tr>")
    print("<td colspan='2' style='padding-bottom: 20px;'><center><input type='submit' name='update' style='background-color: green; border: none; color:white;' value='submit'>")
    print("<a href='login.py' style='background-color: grey; border: none; color:white;'>BACK</a></td>")
    print("</tr>")
    print("</table>")
    print("</form>")
    print("</center>")
    print("</body>")
    print("</html>")

db.close()